((nil . ((projectile-project-compilation-cmd . "make")
         (projectile-project-test-cmd . "./test/bin/btest")
         (eval . (progn
                   (global-set-key (kbd "<f5>") (lambda()
                                                  (interactive)
                                                  (cd (projectile-project-root))
                                                  (shell-command "premake5 gmake")
                                                  ))

                   (global-set-key (kbd "C-<f5>") (lambda()
                                                    (interactive)
                                                    (cd (projectile-project-root))
                                                    (shell-command "premake5 gmake")
                                                    ))
                   )))))
