sudo: required
dist: trusty

language: c

compiler:
    - gcc
    - clang

install:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - debian-sid
        packages:
            - gcc-4.8
            - clang

before_script:
  - curl -sSL https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo -E apt-key add -
  - sudo -E add-apt-repository -y 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libglfw3-dev

script:
    - make
