sudo: false

language: c

compiler:
    - gcc
    - clang

install:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - debian-sid
        packages:
            - gcc-4.8
            - clang
            - ninja-build
            - libglfw3-dev

script:
    - python ./bootstrap.py --ci --cxx=$CC
    - ninja
