# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  TapTracker_config = debug
endif
ifeq ($(config),release)
  TapTracker_config = release
endif

PROJECTS := TapTracker

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

TapTracker:
ifneq (,$(TapTracker_config))
	@echo "==== Building TapTracker ($(TapTracker_config)) ===="
	@${MAKE} --no-print-directory -C . -f TapTracker.make config=$(TapTracker_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f TapTracker.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TapTracker"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"